# Generated by Django 3.2.8 on 2021-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='user_watchlist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
