# Generated by Django 3.2.8 on 2021-12-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_listings_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='user_watchlist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
