# Generated by Django 3.2.8 on 2021-12-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211205_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='listing',
        ),
    ]
