# Generated by Django 3.2.8 on 2021-12-14 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20211214_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='bidder',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='bidder',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
